apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterFlow
metadata:
  name: {{ include "lagoon-logging.fullname" . }}
  labels:
    {{- include "lagoon-logging.labels" . | nindent 4 }}
spec:
  # match entries are considered in order
  # the empty "select: {}" indicates all namespaces/labels
  match:
  - exclude:
      namespaces:
      - {{ .Release.Namespace }}
      {{- with .Values.excludeNamespaces }}
        {{- toYaml . | nindent 6 }}
      {{- end }}
  {{- with .Values.selectNamespaces }}
  - select:
      namespaces:
        {{- toYaml . | nindent 6 }}
  {{- else }}
  - select: {}
  {{- end }}
  filters:
  - tag_normaliser: {}
  outputRefs:
  - {{ include "lagoon-logging.fullname" . }}
