{{- if .Values.logsDispatcher.serviceAccount.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: {{ include "lagoon-logging.logsDispatcher.fullname" . }}
  labels:
    {{- include "lagoon-logging.logsDispatcher.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "lagoon-logging.logsDispatcher.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
{{- end }}
