{{- if .Values.logsTeeRouter.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lagoon-logging.logsTeeRouter.fullname" . }}
  labels:
    {{- include "lagoon-logging.logsTeeRouter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.logsTeeRouter.replicaCount }}
  selector:
    matchLabels:
      {{- include "lagoon-logging.logsTeeRouter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "lagoon-logging.logsTeeRouter.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "lagoon-logging.logsTeeRouter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.logsTeeRouter.podSecurityContext | nindent 8 }}
      containers:
        - name: socat
          securityContext:
            {{- toYaml .Values.logsTeeRouter.securityContext | nindent 12 }}
          image: "{{ .Values.logsTeeRouter.image.repository }}:{{ .Values.logsTeeRouter.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.logsTeeRouter.image.pullPolicy }}
          args:
          # UDP port in
          - {{ .Values.logsTeeRouter.listenPort | quote }}
          # UDP endpoints out
          - {{ include "lagoon-logging.logsDispatcher.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:5141
          {{- with .Values.logsTeeRouter.endpoints }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          ports:
          - containerPort: {{ .Values.logsTeeRouter.listenPort }}
            protocol: UDP
            name: syslog-router
          readinessProbe:
            exec:
              command:
              - pgrep
              - socat
            initialDelaySeconds: 20
          livenessProbe:
            exec:
              command:
              - pgrep
              - socat
            initialDelaySeconds: 120
          resources:
            {{- toYaml .Values.logsTeeRouter.resources | nindent 12 }}
      {{- with .Values.logsTeeRouter.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.logsTeeRouter.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.logsTeeRouter.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
{{- if .Values.logsTeeApplication.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lagoon-logging.logsTeeApplication.fullname" . }}
  labels:
    {{- include "lagoon-logging.logsTeeApplication.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.logsTeeApplication.replicaCount }}
  selector:
    matchLabels:
      {{- include "lagoon-logging.logsTeeApplication.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "lagoon-logging.logsTeeApplication.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "lagoon-logging.logsTeeApplication.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.logsTeeApplication.podSecurityContext | nindent 8 }}
      containers:
        - name: socat
          securityContext:
            {{- toYaml .Values.logsTeeApplication.securityContext | nindent 12 }}
          image: "{{ .Values.logsTeeApplication.image.repository }}:{{ .Values.logsTeeApplication.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.logsTeeApplication.image.pullPolicy }}
          args:
          # UDP port in
          - {{ .Values.logsTeeApplication.listenPort | quote }}
          # UDP endpoints out
          - {{ include "lagoon-logging.logsDispatcher.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:5140
          {{- with .Values.logsTeeApplication.endpoints }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          ports:
          - containerPort: {{ .Values.logsTeeApplication.listenPort }}
            protocol: UDP
            name: application
          readinessProbe:
            exec:
              command:
              - pgrep
              - socat
            initialDelaySeconds: 20
          livenessProbe:
            exec:
              command:
              - pgrep
              - socat
            initialDelaySeconds: 120
          resources:
            {{- toYaml .Values.logsTeeApplication.resources | nindent 12 }}
      {{- with .Values.logsTeeApplication.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.logsTeeApplication.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.logsTeeApplication.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
