apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "lagoon-logging.logsDispatcher.fullname" . }}-env
  labels:
    {{- include "lagoon-logging.logsDispatcher.labels" . | nindent 4 }}
stringData:
  LOGS_FORWARD_USERNAME: {{ required "A valid .Values.forward.username required!" .Values.forward.username }}
  LOGS_FORWARD_PASSWORD: {{ required "A valid .Values.forward.password required!" .Values.forward.password }}
  # self hostname should match the CN on the client certificate
  LOGS_FORWARD_SELF_HOSTNAME: {{ required "A valid .Values.forward.selfHostname required!" .Values.forward.selfHostname }}
  LOGS_FORWARD_SHARED_KEY: {{ required "A valid .Values.forward.sharedKey required!" .Values.forward.sharedKey }}
{{- if .Values.lagoonLogs.enabled }}
  RABBITMQ_USER: {{ required "If .Values.lagoonLogs.enabled is true, a valid .Values.lagoonLogs.rabbitMQUser required!" .Values.lagoonLogs.rabbitMQUser }}
  RABBITMQ_PASSWORD: {{ required "If .Values.lagoonLogs.enabled is true, a valid .Values.lagoonLogs.rabbitMQPassword required!" .Values.lagoonLogs.rabbitMQPassword }}
{{- end }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "lagoon-logging.logsDispatcher.fullname" . }}-tls
  labels:
    {{- include "lagoon-logging.logsDispatcher.labels" . | nindent 4 }}
stringData:
  ca.crt: |
    {{- required "A valid .Values.tls.caCert required!" .Values.tls.caCert | nindent 4 }}
  client.crt: |
    {{- required "A valid .Values.tls.clientCert required!" .Values.tls.clientCert | nindent 4 }}
  client.key: |
    {{- required "A valid .Values.tls.clientKey required!" .Values.tls.clientKey | nindent 4 }}
