apiVersion: v1
kind: Service
metadata:
  name: {{ include "lagoon-logging.logsDispatcher.fullname" . }}
  labels:
    {{- include "lagoon-logging.logsDispatcher.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "lagoon-logging.logsDispatcher.selectorLabels" . | nindent 4 }}
  ports:
  - name: forward
    port: 24224
    protocol: TCP
    targetPort: forward
  - name: metrics
    port: 24231
    protocol: TCP
    targetPort: metrics
  - name: application
    port: 5140
    protocol: UDP
    targetPort: application
  - name: syslog-router
    port: 5141
    protocol: UDP
    targetPort: syslog-router
