apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nginx-php-persistent.fullname" . }}
  labels:
    {{- include "nginx-php-persistent.labels" . | nindent 4 }}
  annotations:
    {{- include "nginx-php-persistent.annotations" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nginx-php-persistent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nginx-php-persistent.labels" . | nindent 8 }}
        {{- include "nginx-php-persistent.datadogLabels" . | nindent 8 }}
      annotations:
        {{- include "nginx-php-persistent.annotations" . | nindent 8 }}
        lagoon.sh/configMapSha: {{ .Values.configMapSha | quote }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: {{ include "nginx-php-persistent.persistentStorageName" . }}
          persistentVolumeClaim:
            claimName: {{ include "nginx-php-persistent.persistentStorageName" . }}
        - name: {{ include "nginx-php-persistent.twig-storage.name" . | quote }}
          emptyDir: {}
      priorityClassName: {{ include "nginx-php-persistent.lagoonPriority" . }}
      enableServiceLinks: false
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{/* This is a test for "rootless" configuration. It will be true if the ROOTLESS_WORKLOAD feature flag is enabled. */}}
      {{- if eq (int .Values.podSecurityContext.fsGroup) 10001 }}
      # This initContainer sets permissions on the RWX storage compatible with
      # the pod securityContext.
      initContainers:
        - command:
            - "sh"
            - "-c"
            - |
              set -e
              SENTINEL="/storage/.lagoon-rootless-migration-complete"
              if ! [ -f "$SENTINEL" ]; then
                find /storage -exec chown {{ .Values.podSecurityContext.runAsUser }}:0 {} +
                find /storage -exec chmod a+r,u+w {} +
                find /storage -type d -exec chmod a+x {} +
                touch "$SENTINEL"
              fi
          image: busybox:musl
          imagePullPolicy: IfNotPresent
          name: fix-storage-permissions
          securityContext:
            runAsUser: 0
          volumeMounts:
            - mountPath: /storage
              name: {{ include "nginx-php-persistent.persistentStorageName" . }}
      {{- end }}
      containers:
        - image: {{ .Values.images.nginx | quote }}
          name: "nginx"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /nginx_status
              port: 50000
            initialDelaySeconds: 1
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /nginx_status
              port: 50000
            initialDelaySeconds: 90
            timeoutSeconds: 3
            failureThreshold: 5
          env:
            ## LAGOON_GIT_SHA is injected directly and not loaded via `lagoon-env` config
            ## This will cause the pod to redeploy on every deployment, even the files have not changed
            - name: LAGOON_GIT_SHA
              value: {{ .Values.gitSha | quote }}
            - name: NGINX_FASTCGI_PASS
              value: '127.0.0.1'
            - name: CRONJOBS
              value: {{ .Values.inPodCronjobs | quote }}
          envFrom:
            - configMapRef:
                name: lagoon-env
          volumeMounts:
            - name: {{ include "nginx-php-persistent.persistentStorageName" . }}
              mountPath: {{ .Values.persistentStorage.path | quote }}
          resources:
            {{- toYaml .Values.resources.nginx | nindent 12 }}

        - image: {{ .Values.images.php | quote }}
          name: "php"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: 9000
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 2
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 60
            periodSeconds: 10
          envFrom:
            - configMapRef:
                name: lagoon-env
          env:
            # LAGOON_GIT_SHA is injected directly and not loaded via `lagoon-env` config
            # This will cause the pod to redeploy on every deployment, even the files have not changed
            - name: LAGOON_GIT_SHA
              value: {{ .Values.gitSha | quote }}
            - name: NGINX_FASTCGI_PASS
              value: '127.0.0.1'
          volumeMounts:
            - name: {{ include "nginx-php-persistent.persistentStorageName" . }}
              mountPath: {{ .Values.persistentStorage.path | quote }}
            - name: {{ include "nginx-php-persistent.twig-storage.name" . | quote }}
              mountPath: {{ include "nginx-php-persistent.twig-storage.path" . | quote }}
          resources:
            {{- toYaml .Values.resources.php | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
