version: '2'
services:
  webhook-handler:
    build:
      context: .
      dockerfile: services/webhook-handler/Dockerfile
    command: yarn run dev
  rabbitmq:
    build:
      context: .
      dockerfile: services/rabbitmq/Dockerfile
  openshiftremove:
    build:
      context: .
      dockerfile: services/openshiftremove/Dockerfile
    command: yarn run dev
  openshiftremove-resources:
    build:
      context: .
      dockerfile: services/openshiftremove-resources/Dockerfile
    command: yarn run dev
  openshiftdeploy:
    build:
      context: .
      dockerfile: services/openshiftdeploy/Dockerfile
    command: yarn run dev
    environment:
      - OC_BUILD_DEPLOY_IMAGE_LOCATION=absolute
      - DOCKER_RUN_PARARM=--network=lagoon_default
      - CI_OVERRIDE_IMAGE_REPO=${BUILD_TAG}
  logs2slack:
    build:
      context: .
      dockerfile: services/logs2slack/Dockerfile
    command: yarn run dev
  webhooks2tasks:
    build:
      context: .
      dockerfile: services/webhooks2tasks/Dockerfile
    command: yarn run dev
  rest2tasks:
    build:
      context: .
      dockerfile: services/rest2tasks/Dockerfile
    command: yarn run dev
  api:
    build:
      context: .
      dockerfile: services/api/Dockerfile
    command: yarn run dev
    environment:
      - GIT_REPOSITORY=http://git:8080/git/hiera.git
    volumes:
      - .:/lagoon
    depends_on:
      - local-hiera-watcher-pusher
  auth-ssh:
    build:
      context: .
      dockerfile: services/auth-ssh/Dockerfile
      args:
        BUILD_TAG: ${BUILD_TAG}
    links:
      - api
      - auth-server
    environment:
      - AMAZEEIO_AUTH_HOST=http://auth-server:3000
      - AMAZEEIO_API_HOST=http://api:3000
    user: '111111111'
  auth-server:
    build: services/auth-server
    command: yarn run dev
    environment:
      - JWTISSUER=auth-server.dev
      - JWTAUDIENCE=api.dev
    user: '111111111'
  jenkins:
    build:
      context: .
      dockerfile: services/jenkins/Dockerfile
    environment:
      - JENKINS_ADMIN_PASSWORD=admin
  jenkins-slave:
    build:
      context: .
      dockerfile: services/jenkins-slave/Dockerfile
    user: root
    depends_on:
      - jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker-images/ansible-drupal-deploy:/ansible-drupal-deploy
      - ./docker-images/oc-build-deploy:/oc-build-deploy
  tests:
    build:
      context: .
      dockerfile: tests/Dockerfile
    environment:
      - WEBHOOK_HOST=webhook-handler
      - WEBHOOK_PORT=3000
      - WEBHOOK_PROTOCOL=http
      - REST2TASKS_HOST=rest2tasks
      - REST2TASKS_PORT=3000
      - REST2TASKS_PROTOCOL=http
      - OPENSHIFT_ROUTE_SUFFIX=192.168.77.100.nip.io
      - GIT_REPO_PREFIX=git@git:/git/
      - SSH_PRIVATE_KEY=-----BEGIN RSA PRIVATE KEY-----\nMIIJKQIBAAKCAgEAuW/QMG+osFkc9c/kA8C5Ur7acYP+6Ue0X/pCU95IUBoi7l+E\nJNmgwq7dXyp3Y8lLo+eaHEXPDpRMawPBT32W6Z32jV31YfU5cm4YyFlB7S23PYIg\nqA7oldkxG+mVv3rCpVbVqJs32P548DwLlxFNot4+WMVULmdMvgDeMnGuFdcu8tgZ\nVDr6eakr8//D3ASXoGqHrEkrhaUFgke/PP4tLFESYmhuvrWTfmxlUpyYLW10Cb3N\nK+OWrtzy+Y8jHAKWxzgg0FCIlsguoqVthCGE1AVTvNEFRI8ppgWaWREJf9A0DxMw\nXagouF+MJsIaGp+4UCUO3TXapkS/luC++cjzcp4DYCVTU5SFzh13r6TbJB//x1Jc\nBKeFjx7k++gWU93KtUQmrZ+ojLBYsKREpPccg2xFT38SgK++3EaRSB7iXe2pg405\nO/yj9D05YjtlYgsow7nYmo8DYe15mNGamK4RyNenm00hEg7JYdGtCZWb1pWGuMQw\nSrSsHyDUa3K2JrmFM0he8J+xdaOOXB2dpLn7YqDkISzYMdC6s7UTJ90QaHht0B28\nZr/Vnzv9IR2uBXZECxKxHcxDPSUeFnsEZ4dOHXI3o19XWlim6Nl/J3WgnNAb3TQy\n/x6UoKnwpydjZauKTOj6JpL3aecE1qWcAow5dPFILbQBa0MI2KAcvVKVJg0CAwEA\nAQKCAgEAnoFv8GcRRyP0+DyqR3buMkeHCy7rrtWm3b9aALxpDWc54o3ss17+5kp4\nWQdApCAFMuYeOfqF4Y1rwLGmBF9ypuBqRi5BOGlXoHNxZZe+HZFNJxta9KxBrQzI\nyHYilVjGlnOiEAwVcbsa/yYkNg4JUaUsn86UhVGxLFwrkezQBEU6EUQcan47adDs\nDBXcge2++dT1gZPNyt/i1JilY+pUDKSD1XA08XjdyVu4RCQsg/AiFs2RWemg/HlK\ni30JYsDnxwQ4MDgWeORF0Ksc8KuCEYU4LZZxLUg+LnZtl6JTf1gll5ksZ3H81JR/\nhQW3MHjEIGV8ziNhcWwkZEBZncNiK2tNYuY6LiLJuGWLNZm+iySW6FnO8UE1wOg4\nt9n+D37A7dAbm39c92oej2uOWilbXjhuHJUFUPtgMDZJAvLxMtPliF9dFG5l8Kly\nuvYaTg1L5DuekOP8HjNuWwV3Wb21jeW0A/RUf7h/VKq/q/F3BbQE6wyxDUVofsMF\n9fwYqrrOMKIXPsnhk46i43TW2r3ygaYv2q56B2uM0mhfeHbrHjqnUwUS/l9cp8YC\ncsOsTn8AYCHe5fo1zv7Xto/C83wV6qQLwqOpWVkvaVYoGwhBFeTYHpV1/ata4UKA\nOtO6cAC/M9DrnWHKjhdmEshqni/G2niab8OkZkMZvRuBtD5r9bUCggEBAN5QRWnk\nBG8SRcPq87eul1pTSwoIDj1ya3CPxdI7YFCiwblYbg7dfsuEK+iSVRQCl4vGs1gR\nVLwyVNBYvl9AInKvH1zeBVXLKOwafz/ddPElbMkhjsKIc7ipvQ5HIY4rPaJCklol\nuhDD0315rmd62fh3B1fSZaJ8ARwRraavmpaMsZvaDLIeA7iiG7mm+YYsjI6G2HW3\nHR7V7sTBq/yIY5YJUtBjZRxi5E0hkRmX3xmy/rEaBsyFhTBBqrHzlfun1dr1nJbh\naTocMdvPb1uByy+PQ/u6V1k3asEAUDEBSDAQWGylivINObXJ7SRQD9UibsqA6J9j\nwrXLkkTINSP6JJsCggEBANWJD4T60kGZC8A5Fhz7wgBh/NNKxIY4eYkQCWSud0iW\ncZ7TChIcBj5V/WQiVt8IGc4c7cPkvhHu66ZPBChUNj0BG5xNzBkpILi3zn3x5qRB\ntiISFI6DOoHNfma05Ok9KJI2v4vS6e1BLIF34Npi0KoxOfycJVb3N4jQLBc5eZSr\nbvyD74/3BByWFNvr4sE1PpTo6Hs5WOzTXzi0qinhOPDc4TwCbr4ggiKzsQAzqU4z\nEXY37pUeH7CTHSBidCaW47m428T5VJSL3TFKwYcuE7ZkprjQT0FiLgea4/+KQ0US\nMFUM6OO/4qtKcuocDGe+Mrut3T0kCmnSosIxx3g/hncCggEAYB/TM6r8483Bzqmb\ngdOC6/JR4t+C0LzVidEQlwtHZPZKz0pWJCVPes4GckQ7dzB7uFtNFoo/2jPlCkUk\n42iGvJHN/MifA+6ZHiWC2el2dAJbnEffQ2vepXz3GuJUtvUpbCxevY3Mew1BN+LS\nLzomX1GQIj/95Bi8Hhfivsz1CZ2B+kJ49NcXgtDNLiPthj9i8wmJNLTdaYTU/cxE\nAigy7x/O5/3iLTjxQAyAgdFyDNmhWJBJWkttQGVUWidZtXtnc4p5j5+dcRvZzxJN\nMwLXCRRoL8Ltm8zjYtow0k+cl/OpWCjoACsJxfmuiOH5Ro3h27uLWce33AVOlGEA\n4TJ6ewKCAQAScrryhDDyFeTcAJKWgnGqUszi/EyqQ+rMGqSVHDWWAdljHVx7YAxy\nCj/QDN9weWSxV/J6wCJjrj6RqbX0PgJJlvTpthbx/YmkK80dOG7ytfKkUuePwGqn\nmDdZbDtyoyQELdKyo9At/Tl5HgBBHdRlP8eAuYTIVKdpnIKSpxaH75+xFTz3NSIX\nzieTMHfwtUbo2o5rRvMV0tUhMwqYf6rJtGuJIbSrnGdh1CBwogX4iZTyn7ZvD6Ex\nQiR8DcV3KAYYn43tIJVcGBFOFuVNZn+xfFSjFuwh+/d6FLmp9CoHp6ChWHIuav+M\nSOxQqYew1s/PQyAgDiMQLXB+UoqnKuXVAoIBAQCBRcSjXWseY+/Uvqj+41kKcEFL\nT7AuJcrb9fpN0EYbrTlaU1yVDfYxnRn4Pw2de1XE/S2dngvriraFHrY/fnyRqM5C\ns/1QnzAjb+y/Vvvt/RaDYXwpm8KpSrd3vqwj7TsoYgWiSvmbjYOg6Gt8QJZNmfhS\nYexGNfR/Zr8jdK9ZC6Tqwt2yUuBtVS3wWmX7Dqz3/kAfJ+tNp7CQNGw7TOMXH071\nfU/ZNna8w+9G3mxSRWM+wxIg7pPZ4floXVJGTcYl6+pG8a1saUNRwx72+pt3XUMD\nXYS+IJhFCIXCuehmfDIp7Fe8Ed2s1QDbF/vdc+icTah12SF/XhZ+6clY8j2Y\n-----END RSA PRIVATE KEY-----
      - SSH_AUTH_HOST=auth-ssh
      - SSH_AUTH_PORT=2020
      - API_HOST=api
      - API_PROTOCOL=http
      - API_PORT=3000
    volumes:
      - ./tests:/ansible
  git:
    build: local-dev/git-server
    environment:
      - GIT_AUTHORIZED_KEYS=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC5b9Awb6iwWRz1z+QDwLlSvtpxg/7pR7Rf+kJT3khQGiLuX4Qk2aDCrt1fKndjyUuj55ocRc8OlExrA8FPfZbpnfaNXfVh9TlybhjIWUHtLbc9giCoDuiV2TEb6ZW/esKlVtWomzfY/njwPAuXEU2i3j5YxVQuZ0y+AN4yca4V1y7y2BlUOvp5qSvz/8PcBJegaoesSSuFpQWCR788/i0sURJiaG6+tZN+bGVSnJgtbXQJvc0r45au3PL5jyMcApbHOCDQUIiWyC6ipW2EIYTUBVO80QVEjymmBZpZEQl/0DQPEzBdqCi4X4wmwhoan7hQJQ7dNdqmRL+W4L75yPNyngNgJVNTlIXOHXevpNskH//HUlwEp4WPHuT76BZT3cq1RCatn6iMsFiwpESk9xyDbEVPfxKAr77cRpFIHuJd7amDjTk7/KP0PTliO2ViCyjDudiajwNh7XmY0ZqYrhHI16ebTSESDslh0a0JlZvWlYa4xDBKtKwfINRrcrYmuYUzSF7wn7F1o45cHZ2kuftioOQhLNgx0LqztRMn3RBoeG3QHbxmv9WfO/0hHa4FdkQLErEdzEM9JR4WewRnh04dcjejX1daWKbo2X8ndaCc0BvdNDL/HpSgqfCnJ2Nlq4pM6Pomkvdp5wTWpZwCjDl08UgttAFrQwjYoBy9UpUmDQ== ansible-testing
  hacky-rest2tasks-ui:
    build:
      context: .
      dockerfile: services/hacky-rest2tasks-ui/Dockerfile
    command: yarn run dev
    environment:
      - API=http://api:3000
      - REST2TASKS_URL=http://rest2tasks:3000
  local-hiera-watcher-pusher:
    depends_on:
      - git
    build: local-dev/hiera-watcher-pusher
    environment:
      - SSH_PRIVATE_KEY=-----BEGIN RSA PRIVATE KEY-----\nMIIJKQIBAAKCAgEAuW/QMG+osFkc9c/kA8C5Ur7acYP+6Ue0X/pCU95IUBoi7l+E\nJNmgwq7dXyp3Y8lLo+eaHEXPDpRMawPBT32W6Z32jV31YfU5cm4YyFlB7S23PYIg\nqA7oldkxG+mVv3rCpVbVqJs32P548DwLlxFNot4+WMVULmdMvgDeMnGuFdcu8tgZ\nVDr6eakr8//D3ASXoGqHrEkrhaUFgke/PP4tLFESYmhuvrWTfmxlUpyYLW10Cb3N\nK+OWrtzy+Y8jHAKWxzgg0FCIlsguoqVthCGE1AVTvNEFRI8ppgWaWREJf9A0DxMw\nXagouF+MJsIaGp+4UCUO3TXapkS/luC++cjzcp4DYCVTU5SFzh13r6TbJB//x1Jc\nBKeFjx7k++gWU93KtUQmrZ+ojLBYsKREpPccg2xFT38SgK++3EaRSB7iXe2pg405\nO/yj9D05YjtlYgsow7nYmo8DYe15mNGamK4RyNenm00hEg7JYdGtCZWb1pWGuMQw\nSrSsHyDUa3K2JrmFM0he8J+xdaOOXB2dpLn7YqDkISzYMdC6s7UTJ90QaHht0B28\nZr/Vnzv9IR2uBXZECxKxHcxDPSUeFnsEZ4dOHXI3o19XWlim6Nl/J3WgnNAb3TQy\n/x6UoKnwpydjZauKTOj6JpL3aecE1qWcAow5dPFILbQBa0MI2KAcvVKVJg0CAwEA\nAQKCAgEAnoFv8GcRRyP0+DyqR3buMkeHCy7rrtWm3b9aALxpDWc54o3ss17+5kp4\nWQdApCAFMuYeOfqF4Y1rwLGmBF9ypuBqRi5BOGlXoHNxZZe+HZFNJxta9KxBrQzI\nyHYilVjGlnOiEAwVcbsa/yYkNg4JUaUsn86UhVGxLFwrkezQBEU6EUQcan47adDs\nDBXcge2++dT1gZPNyt/i1JilY+pUDKSD1XA08XjdyVu4RCQsg/AiFs2RWemg/HlK\ni30JYsDnxwQ4MDgWeORF0Ksc8KuCEYU4LZZxLUg+LnZtl6JTf1gll5ksZ3H81JR/\nhQW3MHjEIGV8ziNhcWwkZEBZncNiK2tNYuY6LiLJuGWLNZm+iySW6FnO8UE1wOg4\nt9n+D37A7dAbm39c92oej2uOWilbXjhuHJUFUPtgMDZJAvLxMtPliF9dFG5l8Kly\nuvYaTg1L5DuekOP8HjNuWwV3Wb21jeW0A/RUf7h/VKq/q/F3BbQE6wyxDUVofsMF\n9fwYqrrOMKIXPsnhk46i43TW2r3ygaYv2q56B2uM0mhfeHbrHjqnUwUS/l9cp8YC\ncsOsTn8AYCHe5fo1zv7Xto/C83wV6qQLwqOpWVkvaVYoGwhBFeTYHpV1/ata4UKA\nOtO6cAC/M9DrnWHKjhdmEshqni/G2niab8OkZkMZvRuBtD5r9bUCggEBAN5QRWnk\nBG8SRcPq87eul1pTSwoIDj1ya3CPxdI7YFCiwblYbg7dfsuEK+iSVRQCl4vGs1gR\nVLwyVNBYvl9AInKvH1zeBVXLKOwafz/ddPElbMkhjsKIc7ipvQ5HIY4rPaJCklol\nuhDD0315rmd62fh3B1fSZaJ8ARwRraavmpaMsZvaDLIeA7iiG7mm+YYsjI6G2HW3\nHR7V7sTBq/yIY5YJUtBjZRxi5E0hkRmX3xmy/rEaBsyFhTBBqrHzlfun1dr1nJbh\naTocMdvPb1uByy+PQ/u6V1k3asEAUDEBSDAQWGylivINObXJ7SRQD9UibsqA6J9j\nwrXLkkTINSP6JJsCggEBANWJD4T60kGZC8A5Fhz7wgBh/NNKxIY4eYkQCWSud0iW\ncZ7TChIcBj5V/WQiVt8IGc4c7cPkvhHu66ZPBChUNj0BG5xNzBkpILi3zn3x5qRB\ntiISFI6DOoHNfma05Ok9KJI2v4vS6e1BLIF34Npi0KoxOfycJVb3N4jQLBc5eZSr\nbvyD74/3BByWFNvr4sE1PpTo6Hs5WOzTXzi0qinhOPDc4TwCbr4ggiKzsQAzqU4z\nEXY37pUeH7CTHSBidCaW47m428T5VJSL3TFKwYcuE7ZkprjQT0FiLgea4/+KQ0US\nMFUM6OO/4qtKcuocDGe+Mrut3T0kCmnSosIxx3g/hncCggEAYB/TM6r8483Bzqmb\ngdOC6/JR4t+C0LzVidEQlwtHZPZKz0pWJCVPes4GckQ7dzB7uFtNFoo/2jPlCkUk\n42iGvJHN/MifA+6ZHiWC2el2dAJbnEffQ2vepXz3GuJUtvUpbCxevY3Mew1BN+LS\nLzomX1GQIj/95Bi8Hhfivsz1CZ2B+kJ49NcXgtDNLiPthj9i8wmJNLTdaYTU/cxE\nAigy7x/O5/3iLTjxQAyAgdFyDNmhWJBJWkttQGVUWidZtXtnc4p5j5+dcRvZzxJN\nMwLXCRRoL8Ltm8zjYtow0k+cl/OpWCjoACsJxfmuiOH5Ro3h27uLWce33AVOlGEA\n4TJ6ewKCAQAScrryhDDyFeTcAJKWgnGqUszi/EyqQ+rMGqSVHDWWAdljHVx7YAxy\nCj/QDN9weWSxV/J6wCJjrj6RqbX0PgJJlvTpthbx/YmkK80dOG7ytfKkUuePwGqn\nmDdZbDtyoyQELdKyo9At/Tl5HgBBHdRlP8eAuYTIVKdpnIKSpxaH75+xFTz3NSIX\nzieTMHfwtUbo2o5rRvMV0tUhMwqYf6rJtGuJIbSrnGdh1CBwogX4iZTyn7ZvD6Ex\nQiR8DcV3KAYYn43tIJVcGBFOFuVNZn+xfFSjFuwh+/d6FLmp9CoHp6ChWHIuav+M\nSOxQqYew1s/PQyAgDiMQLXB+UoqnKuXVAoIBAQCBRcSjXWseY+/Uvqj+41kKcEFL\nT7AuJcrb9fpN0EYbrTlaU1yVDfYxnRn4Pw2de1XE/S2dngvriraFHrY/fnyRqM5C\ns/1QnzAjb+y/Vvvt/RaDYXwpm8KpSrd3vqwj7TsoYgWiSvmbjYOg6Gt8QJZNmfhS\nYexGNfR/Zr8jdK9ZC6Tqwt2yUuBtVS3wWmX7Dqz3/kAfJ+tNp7CQNGw7TOMXH071\nfU/ZNna8w+9G3mxSRWM+wxIg7pPZ4floXVJGTcYl6+pG8a1saUNRwx72+pt3XUMD\nXYS+IJhFCIXCuehmfDIp7Fe8Ed2s1QDbF/vdc+icTah12SF/XhZ+6clY8j2Y\n-----END RSA PRIVATE KEY-----
    volumes:
      - ./local-dev/hiera:/home/hiera
