site_name: Lagoon

pages:
- Home: index.md
- Using Lagoon:
  - Overview: using_lagoon/index.md
  - Local Development Environments: using_lagoon/local_development_environments.md
  - Setup a new Project in Lagoon: using_lagoon/setup_project.md
  - Configure Webhooks: using_lagoon/configure_webhooks.md
  - First Deployment: using_lagoon/first_deployment.md
  - Drupal:
    - Getting Drupal ready to run on Lagoon: using_lagoon/drupal/lagoonize.md
    - First Deployment: using_lagoon/drupal/first_deployment.md
    - Drush 9: using_lagoon/drupal/drush9.md
    - Subfolders: using_lagoon/drupal/subfolders.md
    - Services:
      - MariaDB: using_lagoon/drupal/services/mariadb.md
      - Solr: using_lagoon/drupal/services/solr.md
      - Varnish: using_lagoon/drupal/services/varnish.md
      - Redis: using_lagoon/drupal/services/redis.md
  - .lagoon.yml: using_lagoon/lagoon_yml.md
  - .docker-compose.yml: using_lagoon/docker-compose_yml.md
  - Service Types: using_lagoon/service_types.md
  - Build & Deployment Process: using_lagoon/build_deploy_process.md
  - Environment Types: using_lagoon/environment_types.md
  - Environment Variables: using_lagoon/environment_variables.md
  - Workflows: using_lagoon/workflows.md
  - Backups: using_lagoon/backups.md
  - Going Live: using_lagoon/golive.md
  - Logs:
     - Logging: using_lagoon/logging/logging.md
     - Kibana Examples: using_lagoon/logging/kibana_examples.md
  - Remote Shell: using_lagoon/remote_shell.md
  - GraphQL API: using_lagoon/graphql_api.md
  - Node.js:
    - Gracefull Shutdown: using_lagoon/nodejs/gracefull_shutdown.md
  - Migrations:
    - From amazee.io: using_lagoon/migrations/amazeeio.md
- Administration:
  - Installing Lagoon: administering_lagoon/install.md
  - OpenShift Requirements: administering_lagoon/openshift_requirements.md
  - GraphQL API: administering_lagoon/graphql_api.md
  - Role Based Access Control: administering_lagoon/rbac.md
- Docker Images:
  - Elasticsearch: using_lagoon/docker_images/elasticsearch.md
  - MariaDB Drupal: using_lagoon/docker_images/mariadb-drupal.md
  - MariaDB: using_lagoon/docker_images/mariadb.md
  - MongoDB: using_lagoon/docker_images/mongo.md
  - Nginx Drupal: using_lagoon/docker_images/nginx-drupal.md
  - Nginx: using_lagoon/docker_images/nginx.md
  - PHP CLI Drupal: using_lagoon/docker_images/php-cli-drupal.md
  - PHP CLI: using_lagoon/docker_images/php-cli.md
  - PHP-FPM: using_lagoon/docker_images/php-fpm.md
  - Postgres: using_lagoon/docker_images/postgres.md
  - RabbitMQ: using_lagoon/docker_images/rabbitmq.md
  - Redis Permanent: using_lagoon/docker_images/redis-permanent.md
  - Redis: using_lagoon/docker_images/redis.md
  - Solr Drupal: using_lagoon/docker_images/solr-drupal.md
  - Solr: using_lagoon/docker_images/solr.md
  - Varnish Drupal: using_lagoon/docker_images/varnish-drupal.md
  - Varnish: using_lagoon/docker_images/varnish.md
- Development:
  - Developing Lagoon: developing_lagoon/index.md
  - Tests: developing_lagoon/tests.md
  - Contributing: developing_lagoon/contributing.md
  - API Debugging: developing_lagoon/api-debugging.md
- Code Of Conduct: code_of_conduct.md
theme: readthedocs

markdown_extensions:
  - toc:
      permalink: true
      baselevel: 1
  - admonition
