site_name: Lagoon

pages:
- Home: index.md
- Using Lagoon:
  - Overview: using_lagoon/index.md
  - Local Development Environments: using_lagoon/local_development_environments.md
  - Setup a new Project in Lagoon: using_lagoon/setup_project.md
  - Configure Webhooks: using_lagoon/configure_webhooks.md
  - First Deployment: using_lagoon/first_deployment.md
  - .lagoon.yml: using_lagoon/lagoon_yml.md
  - .docker-compose.yml: using_lagoon/docker-compose_yml.md
  - Service Types: using_lagoon/service_types.md
  - Build & Deployment Process: using_lagoon/build_deploy_process.md
  - Environment Types: using_lagoon/environment_types.md
  - Environment Files: using_lagoon/environment_files.md
  - Docker Images:
    - PHP-FPM: using_lagoon/docker_images/php-fpm.md
    - Nginx: using_lagoon/docker_images/nginx.md
  - Workflows: using_lagoon/workflows.md
  - Backups: using_lagoon/backups.md
  - Logging: using_lagoon/logging.md
  - Remote Shell: using_lagoon/remote_shell.md
  - GraphQL API: using_lagoon/graphql_api.md
  - Drupal:
    - Getting Drupal ready to run on Lagoon: using_lagoon/drupal/lagoonize.md
    - First Deployment: using_lagoon/drupal/first_deployment.md
    - Drush 9: using_lagoon/drupal/drush9.md
    - Services:
      - MariaDB: using_lagoon/drupal/services/mariadb.md
      - Solr: using_lagoon/drupal/services/solr.md
      - Varnish: using_lagoon/drupal/services/varnish.md
      - Redis: using_lagoon/drupal/services/redis.md
  - Migrations:
    - From amazee.io: using_lagoon/migrations/amazeeio.md
  - GoLive: using_lagoon/golive.md
- Administration:
  - Installing Lagoon: administering_lagoon/install.md
  - OpenShift Requirements: administering_lagoon/openshift_requirements.md
  - GraphQL API: administering_lagoon/graphql_api.md
- Development:
  - Developing Lagoon: developing_lagoon/index.md
  - Tests: developing_lagoon/tests.md
  - Contributing: developing_lagoon/contributing.md
- Code Of Conduct: code_of_conduct.md
theme: readthedocs

markdown_extensions:
  - toc:
      permalink: true
      baselevel: 1
  - admonition
