site_name: Lagoon

pages:
- Home: index.md
- Using Lagoon:
  - Overview: using_lagoon/index.md
  - Local Development Environments: using_lagoon/local_development_environments.md
  - Setup a new Project in Lagoon: using_lagoon/setup_project.md
  - Configure Webhooks: using_lagoon/configure_webhooks.md
  - First Deployment: using_lagoon/first_deployment.md
  - Drupal:
    - Lagoonize: using_lagoon/drupal/lagoonize.md
    - First Deployment: using_lagoon/drupal/first_deployment.md
    - Services:
      - Varnish: using_lagoon/drupal/services/varnish.md
  - Migrations:
    - From amazee.io: using_lagoon/migrations/amazeeio.md
- Administration:
  - Administering Lagoon: administering_lagoon/index.md
  - Installing Lagoon: administering_lagoon/install.md
  - GraphQL API: administering_lagoon/graphql_api.md
- Development:
  - Developing Lagoon: developing_lagoon/index.md
  - Tests: developing_lagoon/tests.md
  - Contributing: developing_lagoon/contributing.md
- Code Of Conduct: code_of_conduct.md
theme: readthedocs

markdown_extensions:
    - toc:
        permalink: true
        baselevel: 1
