# Default values for custom-ingress.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

host: ''
hsts: 'null'
tls_acme: true
insecure: Allow
service: ''
annotations: {}
routeMigrate: false

ingressmonitorcontroller:
  enabled: 'false'
  interval: '60'
  alertContacts: 'unconfigured'

## example fastly block
fastly:
  watch: false
#   serviceId: ''
#   apiSecretName: ''