apiVersion: v1
kind: Service
metadata:
  name: {{ include "solr.fullname" . }}
  labels:
    {{- include "solr.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8983
      protocol: TCP
      name: tcp-8983
  selector:
    {{- include "solr.selectorLabels" . | nindent 4 }}
