apiVersion: v1
kind: Service
metadata:
  name: {{ include "mariadb-single.fullname" . }}
  labels:
    {{- include "mariadb-single.labels" . | nindent 4 }}
  annotations:
    {{- include "mariadb-single.annotations" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3306-tcp
      protocol: TCP
      name: 3306-tcp
  selector:
    {{- include "mariadb-single.selectorLabels" . | nindent 4 }}
