apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rabbitmq.fullname" . }}
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
    {{- if .Values.useSpot }}
    lagoon.sh/spot: {{ .Values.useSpot | quote }}
    {{- end }}
  annotations:
    {{- include "rabbitmq.annotations" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "rabbitmq.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "rabbitmq.labels" . | nindent 8 }}
        {{- include "rabbitmq.datadogLabels" . | nindent 8 }}
        {{- if .Values.useSpot }}
        lagoon.sh/spot: {{ .Values.useSpot | quote }}
        {{- end }}
      annotations:
        {{- include "rabbitmq.annotations" . | nindent 8 }}
        k8up.syn.tools/backupcommand: /bin/sh -c 'tar -cf - -C {{ .Values.persistentStorage.path | quote }} --exclude="lost\+found" . || [ $? -eq 1 ]'
        k8up.syn.tools/file-extension: .{{ include "rabbitmq.fullname" . }}.tar
        lagoon.sh/configMapSha: {{ .Values.configMapSha | quote }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: {{ include "rabbitmq.persistentStorageName" . }}
          persistentVolumeClaim:
            claimName: {{ include "rabbitmq.persistentStorageName" . }}
      priorityClassName: {{ include "rabbitmq.lagoonPriority" . }}
      enableServiceLinks: false
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - image: {{ .Values.image | quote }}
          name: {{ .Chart.Name }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: 5672
              protocol: TCP
            - containerPort: 15672
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 5672
            initialDelaySeconds: 1
            periodSeconds: 3
          livenessProbe:
            tcpSocket:
              port: 5672
            initialDelaySeconds: 90
            timeoutSeconds: 3
            failureThreshold: 5
          envFrom:
            - configMapRef:
                name: lagoon-env
          env:
            - name: CRONJOBS
              value: {{ .Values.inPodCronjobs | quote }}
            - name: RABBITMQ_NODENAME
              value: rabbitmq@localhost
          volumeMounts:
            - name: {{ include "rabbitmq.persistentStorageName" . }}
              mountPath: {{ .Values.persistentStorage.path | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
