apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "redis-persistent.fullname" . }}
  labels:
    {{- include "redis-persistent.labels" . | nindent 4 }}
  annotations:
    {{- include "redis-persistent.annotations" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "redis-persistent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "redis-persistent.labels" . | nindent 8 }}
        {{- include "redis-persistent.datadogLabels" . | nindent 8 }}
      annotations:
        {{- include "redis-persistent.annotations" . | nindent 8 }}
        k8up.syn.tools/backupCommand: /bin/sh -c "/bin/busybox tar -cf - -C {{ .Values.persistentStorage.path }} ."
        k8up.syn.tools/fileExtension: .{{ include "redis-persistent.fullname" . }}.tar
        lagoon.sh/configMapSha: {{ .Values.configMapSha | quote }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: {{ include "redis-persistent.persistentStorageName" . }}
          persistentVolumeClaim:
            claimName: {{ include "redis-persistent.persistentStorageName" . }}
      priorityClassName: {{ include "redis-persistent.lagoonPriority" . }}
      enableServiceLinks: false
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - image: {{ .Values.image | quote }}
          name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - name: 6379-tcp
              containerPort: 6379
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 1
            timeoutSeconds: 1
          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 120
            periodSeconds: 10
          env:
            ## LAGOON_GIT_SHA is injected directly and not loaded via `lagoon-env` config
            ## This will cause the pod to redeploy on every deployment, even the files have not changed
            - name: LAGOON_GIT_SHA
              value: {{ .Values.gitSha | quote }}
            - name: CRONJOBS
              value: {{ .Values.inPodCronjobs | quote }}
          envFrom:
            - configMapRef:
                name: lagoon-env
            - secretRef:
                name: lagoon-external-secrets
          volumeMounts:
            - name: {{ include "redis-persistent.persistentStorageName" . }}
              mountPath: {{ .Values.persistentStorage.path | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
