apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nginx-php.fullname" . }}
  labels:
    {{- include "nginx-php.labels" . | nindent 4 }}
    {{- if .Values.useSpot }}
    lagoon.sh/spot: {{ .Values.useSpot | quote }}
    {{- end }}
  annotations:
    {{- include "nginx-php.annotations" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nginx-php.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nginx-php.labels" . | nindent 8 }}
        {{- include "nginx-php.datadogLabels" . | nindent 8 }}
        {{- if .Values.useSpot }}
        lagoon.sh/spot: {{ .Values.useSpot | quote }}
        {{- end }}
      annotations:
        {{- include "nginx-php.annotations" . | nindent 8 }}
        lagoon.sh/configMapSha: {{ .Values.configMapSha | quote }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      priorityClassName: {{ include "nginx-php.lagoonPriority" . }}
      enableServiceLinks: false
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - image: {{ .Values.images.nginx | quote }}
          name: "nginx"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /nginx_status
              port: 50000
            initialDelaySeconds: 1
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /nginx_status
              port: 50000
            initialDelaySeconds: 90
            timeoutSeconds: 3
            failureThreshold: 5
          env:
            ## LAGOON_GIT_SHA is injected directly and not loaded via `lagoon-env` config
            ## This will cause the pod to redeploy on every deployment, even the files have not changed
            - name: LAGOON_GIT_SHA
              value: {{ .Values.gitSha | quote }}
            - name: NGINX_FASTCGI_PASS
              value: '127.0.0.1'
            - name: CRONJOBS
              value: {{ .Values.inPodCronjobs | quote }}
          envFrom:
            - configMapRef:
                name: lagoon-env
          resources:
            {{- toYaml .Values.resources.nginx | nindent 12 }}

        - image: {{ .Values.images.php | quote }}
          name: "php"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: 9000
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 2
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 60
            periodSeconds: 10
          envFrom:
            - configMapRef:
                name: lagoon-env
          env:
            # LAGOON_GIT_SHA is injected directly and not loaded via `lagoon-env` config
            # This will cause the pod to redeploy on every deployment, even the files have not changed
            - name: LAGOON_GIT_SHA
              value: {{ .Values.gitSha | quote }}
            - name: NGINX_FASTCGI_PASS
              value: '127.0.0.1'
          resources:
            {{- toYaml .Values.resources.php | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
