apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-php.fullname" . }}
  labels:
    {{- include "nginx-php.labels" . | nindent 4 }}
  annotations:
    {{- include "nginx-php.annotations" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "nginx-php.selectorLabels" . | nindent 4 }}
