apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cli-persistent.fullname" . }}
  labels:
    {{- include "cli-persistent.labels" . | nindent 4 }}
  annotations:
    {{- include "cli-persistent.annotations" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cli-persistent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cli-persistent.labels" . | nindent 8 }}
      annotations:
        {{- include "cli-persistent.annotations" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: lagoon-sshkey
          secret:
            defaultMode: 420
            secretName: lagoon-sshkey
        - name: {{ .Values.persistentStorage.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistentStorage.name }}
      priorityClassName: {{ include "cli-persistent.lagoonPriority" . }}
      enableServiceLinks: false
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - image: {{ .Values.image | quote }}
          name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
            - name: CRONJOBS
              value: {{ .Values.cronjobs | quote }}
            ## LAGOON_GIT_SHA is injected directly and not loaded via `lagoon-env` config
            ## This will cause the pod to redeploy on every deployment, even the files have not changed
            - name: LAGOON_GIT_SHA
              value: {{ .Values.gitSha | quote }}
            - name: SERVICE_NAME
              value: {{ .Release.Name | quote }}
          envFrom:
            - configMapRef:
                name: lagoon-env
          volumeMounts:
            - mountPath: /var/run/secrets/lagoon/sshkey/
              name: lagoon-sshkey
              readOnly: true
            - name: {{ .Values.persistentStorage.name }}
              mountPath: {{ .Values.persistentStorage.path | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
