apiVersion: v1
entries:
  lagoon-logging:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2020-07-08T15:23:02.537279009+08:00"
    dependencies:
    - name: logging-operator
      repository: https://kubernetes-charts.banzaicloud.com
      version: ~3.3.0
    description: |
      A Helm chart for Kubernetes which installs the lagoon container and router logs collection system.
    digest: 516961903c4c2fc2d8b39b3a9c8f594bdb5db7a1e70c480b89554e64d7303902
    name: lagoon-logging
    type: application
    urls:
    - lagoon-logging-0.6.1.tgz
    version: 0.6.1
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2020-07-08T15:23:02.527457528+08:00"
    dependencies:
    - name: logging-operator
      repository: https://kubernetes-charts.banzaicloud.com
      version: ~3.2.0
    description: |
      A Helm chart for Kubernetes which installs the lagoon container and router logs collection system.
    digest: 94c4a3b92dad2f23f61a750d3b9b6e69084c93a6775a0051ce990c3528e90f25
    name: lagoon-logging
    type: application
    urls:
    - lagoon-logging-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2020-07-08T15:23:02.522593529+08:00"
    dependencies:
    - name: logging-operator
      repository: https://kubernetes-charts.banzaicloud.com
      version: ~3.0.5
    description: |
      A Helm chart for Kubernetes which installs the lagoon container and router logs collection system.
    digest: 974f04650815b54aacbafcd4539058f7ad4d3d384604b16236e78abe8b5935e1
    name: lagoon-logging
    type: application
    urls:
    - lagoon-logging-0.1.0.tgz
    version: 0.1.0
  lagoon-logs-concentrator:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2020-07-08T15:23:02.538051671+08:00"
    description: A Helm chart for Kubernetes which installs the Lagoon logs-concentrator
      service.
    digest: c66bc7450f61a74cb1e8742c4feb5146c7361e2c04e3171235c1e776ca958327
    name: lagoon-logs-concentrator
    type: application
    urls:
    - lagoon-logs-concentrator-0.2.0.tgz
    version: 0.2.0
  lagoon-remote:
  - apiVersion: v2
    appVersion: 1.4.0
    created: "2020-07-08T15:23:02.539156031+08:00"
    description: A Helm chart to run a lagoon-remote
    digest: 96bc41bc9985cd6a7fbd85a32affea3bbbabdf4baa0cd829e7e3d33fb975ceeb
    name: lagoon-remote
    type: application
    urls:
    - lagoon-remote-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v2
    appVersion: 1.4.0
    created: "2020-07-08T15:23:02.538674677+08:00"
    description: A Helm chart to run a lagoon-remote
    digest: 5756a3fbb46a11f2f43fdcadb41d709d90c70208b90fa0257d48dcacc4df3040
    name: lagoon-remote
    type: application
    urls:
    - lagoon-remote-0.1.2.tgz
    version: 0.1.2
generated: "2020-07-08T15:23:02.517886032+08:00"
