# use for lagoon-deployer to be able to create mariadbconsumer kinds
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mariadbconsumer-role
  labels:
    # Add these permissions to the "admin" and "edit" default roles.
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
- apiGroups: ["mariadb.amazee.io"]
  resources: ["mariadbconsumers"]
  verbs: ["*"]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mariadbprovider-role
  labels:
    # Add these permissions to the "admin" and "edit" default roles.
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
- apiGroups: ["mariadb.amazee.io"]
  resources: ["mariadbproviders"]
  verbs: ["*"]