apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "lagoon-logs-concentrator.fullname" . }}
  labels:
    {{- include "lagoon-logs-concentrator.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  serviceName: {{ include "lagoon-logs-concentrator.fullname" . }}
  selector:
    matchLabels:
      {{- include "lagoon-logs-concentrator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        checksum/env-configmap: {{ include (print $.Template.BasePath "/env.configmap.yaml") . | sha256sum }}
        checksum/fluent-conf-configmap: {{ include (print $.Template.BasePath "/fluent-conf.configmap.yaml") . | sha256sum }}
    {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "lagoon-logs-concentrator.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "lagoon-logs-concentrator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
      - name: chown-buffer
        image: busybox:musl
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        command:
        - chown
        - '100:0'
        - /fluentd/buffer
        volumeMounts:
        - mountPath: /fluentd/buffer/
          name: {{ include "lagoon-logs-concentrator.fullname" . }}-buffer
      containers:
      - name: fluentd
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: forward
          containerPort: 24224
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: forward
        readinessProbe:
          tcpSocket:
            port: forward
        envFrom:
        - secretRef:
            name: {{ include "lagoon-logs-concentrator.fullname" . }}-env
        - configMapRef:
            name: {{ include "lagoon-logs-concentrator.fullname" . }}-env
        volumeMounts:
        - mountPath: /fluentd/etc/fluent.conf
          name: {{ include "lagoon-logs-concentrator.fullname" . }}-fluent-conf
          subPath: fluent.conf
        - mountPath: /fluentd/etc/user.d/
          name: {{ include "lagoon-logs-concentrator.fullname" . }}-users
        - mountPath: /fluentd/buffer/
          name: {{ include "lagoon-logs-concentrator.fullname" . }}-buffer
        - mountPath: /fluentd/tls/
          name: {{ include "lagoon-logs-concentrator.fullname" . }}-tls
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: fluent.conf
            path: fluent.conf
          name: {{ include "lagoon-logs-concentrator.fullname" . }}-fluent-conf
        name: {{ include "lagoon-logs-concentrator.fullname" . }}-fluent-conf
      - secret:
          defaultMode: 420
          secretName: {{ include "lagoon-logs-concentrator.fullname" . }}-tls
        name: {{ include "lagoon-logs-concentrator.fullname" . }}-tls
      - secret:
          defaultMode: 420
          secretName: {{ include "lagoon-logs-concentrator.fullname" . }}-users
        name: {{ include "lagoon-logs-concentrator.fullname" . }}-users
  volumeClaimTemplates:
  - metadata:
      name: {{ include "lagoon-logs-concentrator.fullname" . }}-buffer
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 32Gi
