apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: lagoon-openshift-template-mariadb-galera
parameters:
  - name: SERVICE_NAME
    description: Name of this service
    required: true
  - name: SAFE_BRANCH
    description: Which branch this belongs to, special chars replaced with dashes
    required: true
  - name: SAFE_PROJECT
    description: Which project this belongs to, special chars replaced with dashes
    required: true
  - name: BRANCH
    description: Which branch this belongs to, original value
    required: true
  - name: PROJECT
    description: Which project this belongs to, original value
    required: true
  - name: LAGOON_GIT_SHA
    description: git hash sha of the current deployment
    required: true
  - name: SERVICE_ROUTER_URL
    description: URL of the Router for this service
    value: ""
  - name: OPENSHIFT_PROJECT
    description: Name of the Project that this service is in
    required: true
  - name: REGISTRY
    description: Registry where Images are pushed to
    required: true
  - name: DEPLOYMENT_STRATEGY
    description: Strategy of Deploymentconfig
    value: "Recreate"
objects:
- apiVersion: apps/v1beta1
  kind: StatefulSet
  metadata:
    name: ${SERVICE_NAME}-galera
  spec:
    serviceName: ${SERVICE_NAME}-galera
    replicas: 3
    selector:
      matchLabels:
        service: ${SERVICE_NAME}-galera
    template:
      metadata:
        labels:
          branch: ${SAFE_BRANCH}
          project: ${SAFE_PROJECT}
          service: ${SERVICE_NAME}-galera
        annotations:
          alpha.image.policy.openshift.io/resolve-names: "*"
      spec:
        containers:
        - name: ${SERVICE_NAME}-galera
          image: ${REGISTRY}/${OPENSHIFT_PROJECT}/${SERVICE_NAME}:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 3306
            name: mysql
          - containerPort: 4444
            name: sst
          - containerPort: 4567
            name: replication
          - containerPort: 4568
            name: ist
          readinessProbe:
            exec:
              command:
              - /usr/share/container-scripts/mysql/readiness-probe.sh
            initialDelaySeconds: 15
            timeoutSeconds: 5
          volumeMounts:
          - name: ${SERVICE_NAME}-galera
            mountPath: /var/lib/mysql
            subPath: data
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
    volumeClaimTemplates:
    - metadata:
        name: ${SERVICE_NAME}-galera
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    labels:
      service: ${SERVICE_NAME}
      branch: ${SAFE_BRANCH}
      project: ${SAFE_PROJECT}
    name: ${SERVICE_NAME}-maxscale
  spec:
    replicas: 1
    selector:
      service: ${SERVICE_NAME}
    strategy:
      type: ${DEPLOYMENT_STRATEGY}
    template:
      metadata:
        creationTimestamp: null
        labels:
          service: ${SERVICE_NAME}
          branch: ${SAFE_BRANCH}
          project: ${SAFE_PROJECT}
      spec:
        containers:
        - image: ${REGISTRY}/${OPENSHIFT_PROJECT}/${SERVICE_NAME}:latest
          command:
          - /lagoon/entrypoints.bash
          - /usr/local/bin/maxscale-start
          name: ${SERVICE_NAME}-maxscale
          ports:
          - containerPort: 3306
            protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 15
            timeoutSeconds: 1
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 120
            periodSeconds: 5
          envFrom:
          - configMapRef:
              name: lagoon-env
          env:
          - name: SERVICE_NAME
            value: ${SERVICE_NAME}
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${SERVICE_NAME}-maxscale
        from:
          kind: ImageStreamTag
          name: ${SERVICE_NAME}:latest
      type: ImageChange
