apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "lagoon-remote.kubernetesbuilddeploy.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
subjects:
- kind: ServiceAccount
  name: {{ include "lagoon-remote.kubernetesbuilddeploy.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io