{{- if .Values.dockerHost.storage.create -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "lagoon-remote.dockerHost.fullname" . }}
  labels:
    {{- include "lagoon-remote.dockerHost.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.dockerHost.storage.size | quote }}
{{- end -}}