---
apiVersion: scheduling.k8s.io/v1beta1
kind: PriorityClass
metadata:
  name: lagoon-priority-production
value: 1000000
globalDefault: true
description: "This priority class should be used for production environments."
---
apiVersion: scheduling.k8s.io/v1beta1
kind: PriorityClass
metadata:
  name: lagoon-priority-staging
value: 100000
globalDefault: false
description: "This priority class should be used for staging environments."
---
apiVersion: scheduling.k8s.io/v1beta1
kind: PriorityClass
metadata:
  name: lagoon-priority-development
value: 10000
globalDefault: false
description: "This priority class should be used for development environments."
