# Default values for nginx.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

images:
  nginx: ""
  php: ""

environmentType: production

persistentStorage:
  size: 5Gi

imagePullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8080

## example fastly block
fastly:
  watch: false
#   serviceId: ''
#   apiSecretName: ''

resources:
  nginx:
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    requests:
      cpu: 10m
      memory: 10Mi
  php:
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    requests:
      cpu: 10m
      memory: 10Mi

nodeSelector: {}

tolerations: []

cronjobTolerations: []

affinity: {}

inPodCronjobs: ""

configMapSha: ""