description: The leading tool for querying and visualizing time series and metrics.
engine: gotpl
home: https://grafana.net
icon: https://raw.githubusercontent.com/grafana/grafana/master/public/img/logo_transparent_400x.png
maintainers:
- email: zanhsieh@gmail.com
  name: Ming Hsieh
name: grafana-dpc
sources:
- https://github.com/grafana/grafana
version: 0.5.0
