name: 'Publish UI Storybook to Chromatic'

on:
  push:
    paths:
      - "services/ui/**"
    branches-ignore:
      - "dependabot/**"

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: yarn && yarn --cwd services/api install && yarn --cwd services/api build && yarn --cwd services/ui install && yarn --cwd services/ui build
      - name: Build storybook
        run: yarn workspace ui run build-storybook --loglevel silly
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: services/ui
          storybookBuildDir: storybook-static
          allowConsoleErrors: true
          exitOnceUploaded: true # Exit with status 0 (OK) once the build has been sent to Chromatic
          # exitZeroOnChanges: true # Prevent workflow fail if there are changes
          # autoAcceptChanges: true
